inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 130
  Enabled: true
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 45